log:
  level: info
runner:
  file: .runner
  capacity: 1
  labels:
    - "linux_amd64:host"
    - "ubuntu-latest:docker://ghcr.io/catthehacker/ubuntu:act-latest"
    - "ubuntu-22.04:docker://ghcr.io/catthehacker/ubuntu:act-22.04"
    - "ubuntu-20.04:docker://ghcr.io/catthehacker/ubuntu:act-20.04"
cache:
  enabled: false
container:
  privileged: false
  force_pull: true
  valid_volumes: []
  network: host
  options: "--network=host"
