# Auto-generated by update-gws.sh
{
  version = "0.16.0";
  baseUrl = "https://github.com/googleworkspace/cli/releases/download";
  platforms = {
    "aarch64-darwin" = {
      artifact = "gws-aarch64-apple-darwin.tar.gz";
      hash = "sha256-YCvdlNIPBv+33EuNlq/WIMlzsHhbYFIgc4VbcrdcbXw=";
    };
    "x86_64-darwin" = {
      artifact = "gws-x86_64-apple-darwin.tar.gz";
      hash = "sha256-DxsIn2EEmUmEqDlVzgTG7KCP/KEoTJv2Nu7XlW4hdh4=";
    };
    "aarch64-linux" = {
      artifact = "gws-aarch64-unknown-linux-gnu.tar.gz";
      hash = "sha256-KnT/oYJs5cw0BfI/DNu7vt7P+3/Qyix0mBKWrS9DUF0=";
    };
    "x86_64-linux" = {
      artifact = "gws-x86_64-unknown-linux-gnu.tar.gz";
      hash = "sha256-rEtpZ/EErDITEVwwUr7qKps1B6EPjruss7cX8YPNA/Y=";
    };
  };
}
