# Auto-generated by update-gws.sh
{
  version = "0.8.0";
  baseUrl = "https://github.com/googleworkspace/cli/releases/download";
  platforms = {
    "aarch64-darwin" = {
      artifact = "gws-aarch64-apple-darwin.tar.gz";
      hash = "sha256-k2jJ5YHMJA/RZQSjaX18c3ELei5fxFGmSlaTWO8RZJk=";
    };
    "x86_64-darwin" = {
      artifact = "gws-x86_64-apple-darwin.tar.gz";
      hash = "sha256-DuK0d5NY4pHYQ/VX0hKiBqdGYqVCQBjyU8NU6gchmKw=";
    };
    "aarch64-linux" = {
      artifact = "gws-aarch64-unknown-linux-gnu.tar.gz";
      hash = "sha256-3PTPnyuVwMB5qkhABIfUjx6QrcFE41Q2Fgq4XdtZ06k=";
    };
    "x86_64-linux" = {
      artifact = "gws-x86_64-unknown-linux-gnu.tar.gz";
      hash = "sha256-Sy28OxcWqgy/2R1Z6oltv16JOhUVlMNj8MmOdg4uUEY=";
    };
  };
}
