# Auto-generated by update-herdr.sh
# Pins hashes that depend on the current herdr-src entry in repos-src.nix.
# Do not edit by hand; run ./apps/fetcher/update-herdr.sh.
{
  version = "0.8.1-unstable-2026-08-19";
  cargoHash = "sha256-gQcxVzVihoIktYeAxekGa4kvHOdlXsZ53jpAbSrp0Kc=";
  zigDepsHash = "sha256-PnM+hZIlLyQwK8vJgd/Bhjt1lNIz06T8FahwliRmMrY=";
}
