# This file is auto-generated by npm-refresh
# Do not modify manually - changes will be overwritten
# To update packages, run: npm-refresh packages.toml > npm-packages.nix
{
  "ccstatusline" = {
    "version" = "2.0.18";
    "url" = "https://registry.npmjs.org/ccstatusline/-/ccstatusline-2.0.18.tgz";
    "url-hash" = "sha256-yfxChZhRhoFfeXbsf7riIfVr5IJ5SHh+MRsrYa5STDU=";
  };
  "ccusage" = {
    "version" = "17.0.2";
    "url" = "https://registry.npmjs.org/ccusage/-/ccusage-17.0.2.tgz";
    "url-hash" = "sha256-TWuBDOFetMz80TFicfKZJ90AB3R/wAgG6fezgOBuz+c=";
  };
  "claude-code" = {
    "version" = "1.0.123";
    "url" = "https://registry.npmjs.org/@anthropic-ai/claude-code/-/claude-code-1.0.123.tgz";
    "url-hash" = "sha256-dS/kcZgAzVgWQ6hJNicHdR/sJ1AWj2/NKCC+dr9bA1k=";
  };
  "mermaid-cli" = {
    "version" = "0.2.4";
    "url" = "https://registry.npmjs.org/mermaid-cli/-/mermaid-cli-0.2.4.tgz";
    "url-hash" = "sha256-LNFoy/TmuAY7BJegdIcXVO3gM2HyiF1rjEX92F6u7+o=";
  };
  "tdd-guard" = {
    "version" = "1.0.2";
    "url" = "https://registry.npmjs.org/tdd-guard/-/tdd-guard-1.0.2.tgz";
    "url-hash" = "sha256-SPUc2XqmjVXox/Y+bR2bA5+rYFPMCJl35OrzvbqtD8s=";
  };
}
