# This file is auto-generated by npm-refresh
# Do not modify manually - changes will be overwritten
# To update packages, run: npm-refresh packages.toml > npm-packages.nix
{
  "ccusage" = {
    "version" = "15.9.3";
    "url" = "https://registry.npmjs.org/ccusage/-/ccusage-15.9.3.tgz";
    "url-hash" = "sha256-tVXl0h2MbwIc15JYYeMFFOyKqVHQ4wjhMLakwUK+tcw=";
  };
  "claude-code" = {
    "version" = "1.0.73";
    "url" = "https://registry.npmjs.org/@anthropic-ai/claude-code/-/claude-code-1.0.73.tgz";
    "url-hash" = "sha256-W7LJLgI6ABkKxNDpZ/ekHX/VgS5U3KPkl1K41XjZ6xg=";
  };
  "mermaid-cli" = {
    "version" = "0.2.4";
    "url" = "https://registry.npmjs.org/mermaid-cli/-/mermaid-cli-0.2.4.tgz";
    "url-hash" = "sha256-LNFoy/TmuAY7BJegdIcXVO3gM2HyiF1rjEX92F6u7+o=";
  };
}
