# This file is auto-generated by npm-refresh
# Do not modify manually - changes will be overwritten
# To update packages, run: npm-refresh packages.toml > npm-packages.nix
{
  "ccusage" = {
    "version" = "15.8.0";
    "url" = "https://registry.npmjs.org/ccusage/-/ccusage-15.8.0.tgz";
    "url-hash" = "sha256-wCkE/t06dpw732oZJ1NF6u1Asz2IcWdsqiAgr11EIR4=";
  };
  "claude-code" = {
    "version" = "1.0.72";
    "url" = "https://registry.npmjs.org/@anthropic-ai/claude-code/-/claude-code-1.0.72.tgz";
    "url-hash" = "sha256-PogxJBc/YnEb52qSDJNw11k1rdEDrK8KLmhh/hvVB7o=";
  };
  "mermaid-cli" = {
    "version" = "0.2.4";
    "url" = "https://registry.npmjs.org/mermaid-cli/-/mermaid-cli-0.2.4.tgz";
    "url-hash" = "sha256-LNFoy/TmuAY7BJegdIcXVO3gM2HyiF1rjEX92F6u7+o=";
  };
}
