# Auto-generated by update-pi-ask-user-question.sh
# Pins the juicesharp/rpiv-mono GitHub source (subdir packages/rpiv-ask-user-question)
# for buildNpmPackage.
# Lockfile: pi-ask-user-question-lock.json (generated; upstream has no lockfile).
# Do not edit by hand; run ./apps/fetcher/update-pi-ask-user-question.sh.
{
  version = "1.20.0";
  hash = "sha256-t2WVwhyT7x5D049iot4UDUWp+oM+XDudHbq/nBL/b84=";
  npmDepsHash = "sha256-1jFjY2n6EUNdAUHrUl7jbqyZmdSj0hgP9NWXDwdKb0I=";
}
