# Auto-generated by update-pi.sh
# Built from the earendil-works/pi monorepo via buildNpmPackage (see
# ../pi-coding-agent.nix). Do not edit by hand; run ./apps/fetcher/update-pi.sh.
{
  version = "0.84.1";
  hash = "sha256-lg+I4S/aAjazjhGZU567ow+rksoNiqOqjHl//TjAMes=";
  npmDepsHash = "sha256-tufyZQRPAUeDtiq0UQodbKA/Y9xUAvNT8K+NWFjkeME=";
  piAiDataHash = "sha256-araJGJ58s95c2xJjEqPmDorDX+XuXxtj0A9xHIpDDHM=";
}
