# Auto-generated by update-pi.sh
# Built from the earendil-works/pi monorepo via buildNpmPackage (see
# ../pi-coding-agent.nix). Do not edit by hand; run ./apps/fetcher/update-pi.sh.
{
  version = "0.87.1";
  hash = "sha256-GUhlq6t+l6iiViOZ0bkV28v3ZDqcLvEwpZpYZ5JAyDk=";
  npmDepsHash = "sha256-JBIYoP2vvRNz1HONNvDJ1U3c+nmCJ7/VgNthRTkrkIA=";
  piAiDataHash = "sha256-NbRDLyfMJmX4a+67mvajmxJRlwiDwwRL2L5PToxzHKA=";
}
