# Auto-generated by update-pi.sh
# Built from the earendil-works/pi monorepo via buildNpmPackage (see
# ../pi-coding-agent.nix). Do not edit by hand; run ./apps/fetcher/update-pi.sh.
{
  version = "0.82.1";
  hash = "sha256-LESpgd/KUoNqdBfnd1oyMN8coKm0Odbo9GYkUDry8Zk=";
  npmDepsHash = "sha256-5pHRwxpKg95/phOcYHeWdvPJNtSOhiw7PRoVxsuh0RM=";
  piAiDataHash = "sha256-L535UigItiHNNEmHZTfwPYqN+LjX7C1bGMapEKqFtJA=";
}
