# Auto-generated by update-pi-dynamic-workflows.sh
# Pins the @quintinshaw/pi-dynamic-workflows npm tarball plus its single runtime
# dependency (acorn). Assembled into a loadable pi package by
# ../pi-dynamic-workflows.nix. Do not edit by hand; run the updater.
{
  workflows = {
    version = "2.9.0";
    url = "https://registry.npmjs.org/@quintinshaw/pi-dynamic-workflows/-/pi-dynamic-workflows-2.9.0.tgz";
    hash = "sha256-MTcFTPq4dSLSs8WQrzfRAi1irnPiM9oIwBRG1dWuPx4=";
  };
  acorn = {
    version = "8.17.0";
    url = "https://registry.npmjs.org/acorn/-/acorn-8.17.0.tgz";
    hash = "sha256-r6g//3UebJc57qVS2EMoQU04YECPmM5cfzzH4qOZZCQ=";
  };
}
