# Auto-generated by hand — bump with:
#   nix-prefetch-url --unpack https://github.com/HazAT/pi-interactive-subagents/archive/<rev>.tar.gz
# then convert with:
#   nix hash to-sri --type sha256 <base32>
{
  version = "3.7.2";
  rev = "c100577ebf7393a11d098ad9810ec6c269dcfc30";
  hash = "sha256-5tVpk/OYBqy9KlSFuFTg8KKfirwkygQ3sN8bfQOyxno=";
}
