# Auto-generated by update-pi-mcp-adapter.sh
# Pins the nicobailon/pi-mcp-adapter GitHub source for buildNpmPackage.
# Lockfile: pi-mcp-adapter-lock.json (generated; upstream repo has no lockfile).
# Do not edit by hand; run ./apps/fetcher/update-pi-mcp-adapter.sh.
{
  version = "2.26.1";
  hash = "sha256-9iKfraMl03Pg/3NhoUZgpuzEaPBxK5j+qZ0deWCPnbM=";
  npmDepsHash = "sha256-XOccXuaCf72a3zfXAsKfsb2dnA1ld2xwzVr+z3y2pZE=";
}
