# Auto-generated by update-pi-web-access.sh
# Pins the nicobailon/pi-web-access GitHub source for buildNpmPackage.
# Lockfile: pi-web-access-lock.json (generated; upstream repo has no lockfile).
# Do not edit by hand; run ./apps/fetcher/update-pi-web-access.sh.
{
  version = "0.25.0";
  hash = "sha256-Ad8H3vdY4zOivqqWhQd+FWhL0DGtFtGG4TY+w7eCFqk=";
  npmDepsHash = "sha256-kwRxZzb8s00ul9DJDTYeNiVejmps8WrQtshcvy7gBPM=";
}
