# Auto-generated by update-pi-web-access.sh
# Pins the nicobailon/pi-web-access GitHub source for buildNpmPackage.
# Lockfile: pi-web-access-lock.json (generated; upstream repo has no lockfile).
# Do not edit by hand; run ./apps/fetcher/update-pi-web-access.sh.
{
  version = "0.28.0";
  hash = "sha256-oPUUqlxPUUxOmt9ZrM1RnXynGwFi0hkHhug/jC4ZbVk=";
  npmDepsHash = "sha256-uauY9nX1iR+Y9MvX/ls9wvlqb26XDOcinPgbYbnuU2Y=";
}
