# Auto-generated by update-pi-web-access.sh
# Pins the nicobailon/pi-web-access GitHub source for buildNpmPackage.
# Lockfile: pi-web-access-lock.json (generated; upstream repo has no lockfile).
# Do not edit by hand; run ./apps/fetcher/update-pi-web-access.sh.
{
  version = "0.23.0";
  hash = "sha256-q/TZUkgeC/W/Ft7RMVIDc6m/Dsj2amicHhSeCbzk05E=";
  npmDepsHash = "sha256-TUOiefsKK1rbjn2PGUfuanLHg39bm08NvMOZTVMqfLo=";
}
