#!/usr/bin/env bash
# Update gws-binary.nix with latest version from GitHub releases

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NIX_FILE="$SCRIPT_DIR/gws-binary.nix"

# Fetch latest version from GitHub API
version=$(curl -fsSL "https://api.github.com/repos/googleworkspace/cli/releases/latest" | jq -r '.tag_name' | sed 's/^v//')
echo "Fetching GWS CLI version: $version"

BASE_URL="https://github.com/googleworkspace/cli/releases/download/v${version}"

# Platform artifacts to fetch
declare -A ARTIFACTS=(
  ["aarch64-darwin"]="gws-aarch64-apple-darwin.tar.gz"
  ["x86_64-darwin"]="gws-x86_64-apple-darwin.tar.gz"
  ["aarch64-linux"]="gws-aarch64-unknown-linux-gnu.tar.gz"
  ["x86_64-linux"]="gws-x86_64-unknown-linux-gnu.tar.gz"
)

# Prefetch all hashes
declare -A HASHES
for platform in "${!ARTIFACTS[@]}"; do
  artifact="${ARTIFACTS[$platform]}"
  echo "Prefetching $artifact..."
  hash=$(nix hash convert --hash-algo sha256 --to sri "sha256:$(nix-prefetch-url --type sha256 "$BASE_URL/$artifact" 2>/dev/null)")
  HASHES[$platform]="$hash"
done

# Generate nix file
{
  cat <<EOF
# Auto-generated by update-gws.sh
{
  version = "$version";
  baseUrl = "https://github.com/googleworkspace/cli/releases/download";
  platforms = {
EOF

  for platform in aarch64-darwin x86_64-darwin aarch64-linux x86_64-linux; do
    cat <<EOF
    "$platform" = {
      artifact = "${ARTIFACTS[$platform]}";
      hash = "${HASHES[$platform]}";
    };
EOF
  done

  cat <<EOF
  };
}
EOF
} > "$NIX_FILE"

alejandra --quiet "$NIX_FILE"
echo "Updated $NIX_FILE"
