#!/usr/bin/env bash
# Update pi-coding-agent.nix with the latest release from earendil-works/pi.
# Pi is built from the monorepo source via buildNpmPackage (see
# ../pi-coding-agent.nix), so we pin the GitHub source hash + the npm deps hash.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NIX_FILE="$SCRIPT_DIR/pi-coding-agent.nix"

# Latest published version (npm and the GitHub tag track together).
version=$(npm view @earendil-works/pi-coding-agent version)
echo "Fetching pi-coding-agent version: $version"

# Source tarball hash (NAR hash, usable directly as fetchFromGitHub hash).
prefetch=$(nix flake prefetch --json "github:earendil-works/pi/v${version}")
hash=$(echo "$prefetch" | jq -r '.hash')
storePath=$(echo "$prefetch" | jq -r '.storePath')

# Vendored npm dependencies hash, computed from the monorepo lockfile.
echo "Computing npmDepsHash from $storePath/package-lock.json ..."
npmDepsHash=$(nix run nixpkgs#prefetch-npm-deps -- "$storePath/package-lock.json" 2>/dev/null)

# Pi's source tags omit generated pi-ai provider data. The published pi-ai
# tarball includes it, so pin that artifact for the package build.
piAiDataHash=$(nix store prefetch-file --json "https://registry.npmjs.org/@earendil-works/pi-ai/-/pi-ai-${version}.tgz" | jq -r '.hash')

cat > "$NIX_FILE" <<EOF
# Auto-generated by update-pi.sh
# Built from the earendil-works/pi monorepo via buildNpmPackage (see
# ../pi-coding-agent.nix). Do not edit by hand; run ./apps/fetcher/update-pi.sh.
{
  version = "${version}";
  hash = "${hash}";
  npmDepsHash = "${npmDepsHash}";
  piAiDataHash = "${piAiDataHash}";
}
EOF

alejandra --quiet "$NIX_FILE"
echo "Updated $NIX_FILE"
