#!/usr/bin/env bash
# Update hashes for the local herdr package.
#
# Source is pinned through repos.toml/repos-src.nix by update-fetcher-repos.
# This script refreshes the hashes that depend on that source: Cargo vendor
# deps and Zig deps for the vendored libghostty-vt build.

set -euo pipefail

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
PIN_FILE="$ROOT/apps/fetcher/herdr.nix"
FAKE_HASH="sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="

cd "$ROOT"

metadata=$(nix flake metadata --json github:ogulcancelik/herdr)
last_modified=$(printf '%s' "$metadata" | jq -r '.locked.lastModified')
if version_date=$(date -u -r "$last_modified" +%Y-%m-%d 2>/dev/null); then
  :
else
  version_date=$(date -u -d "@$last_modified" +%Y-%m-%d)
fi

src_expr='let
  flake = builtins.getFlake (toString ./.);
  pkgs = import flake.inputs.nixpkgs { system = builtins.currentSystem; };
  repos = import ./apps/fetcher/repos-src.nix { inherit pkgs; };
in
  repos.herdr-src.outPath'
src_path=$(nix eval --raw --impure --expr "$src_expr")
base_version=$(awk -F '"' '/^version = / { print $2; exit }' "$src_path/Cargo.toml")
version="$base_version-unstable-$version_date"

format_nix() {
  if command -v alejandra >/dev/null 2>&1; then
    alejandra --quiet "$@"
  else
    nix run nixpkgs#alejandra -- --quiet "$@"
  fi
}

write_pin() {
  local cargo_hash="$1"
  local zig_deps_hash="$2"

  cat > "$PIN_FILE" <<EOF
# Auto-generated by update-herdr.sh
# Pins hashes that depend on the current herdr-src entry in repos-src.nix.
# Do not edit by hand; run ./apps/fetcher/update-herdr.sh.
{
  version = "$version";
  cargoHash = "$cargo_hash";
  zigDepsHash = "$zig_deps_hash";
}
EOF
  format_nix "$PIN_FILE"
}

build_expr='let
  flake = builtins.getFlake (toString ./.);
  pkgs = import flake.inputs.nixpkgs { system = builtins.currentSystem; };
in
  pkgs.callPackage ./apps/herder.nix {}'

old_pin=$(mktemp)
cp "$PIN_FILE" "$old_pin"
ok=0
cleanup() {
  if [ "$ok" -ne 1 ]; then
    cp "$old_pin" "$PIN_FILE"
  fi
  rm -f "$old_pin"
}
trap cleanup EXIT

cargo_hash="$FAKE_HASH"
zig_deps_hash="$FAKE_HASH"
write_pin "$cargo_hash" "$zig_deps_hash"

for _ in 1 2 3 4; do
  echo "Building herdr to validate/update dependency hashes..."
  if build_output=$(nix build --no-link --impure --expr "$build_expr" 2>&1); then
    ok=1
    echo "Updated $PIN_FILE ($version)"
    exit 0
  fi

  got_hash=$(printf '%s\n' "$build_output" | awk '/got:[[:space:]]+sha256-/ { print $2; exit }')
  if [ -z "${got_hash:-}" ]; then
    printf '%s\n' "$build_output" >&2
    echo "Could not find a Nix hash mismatch in build output." >&2
    exit 1
  fi

  if printf '%s\n' "$build_output" | grep -q -- '-zig-deps\.drv'; then
    zig_deps_hash="$got_hash"
    echo "  zigDepsHash: $zig_deps_hash"
  elif printf '%s\n' "$build_output" | grep -q -- '-vendor'; then
    cargo_hash="$got_hash"
    echo "  cargoHash: $cargo_hash"
  else
    printf '%s\n' "$build_output" >&2
    echo "Could not identify which herdr hash changed." >&2
    exit 1
  fi

  write_pin "$cargo_hash" "$zig_deps_hash"
done

echo "herdr hash update did not converge." >&2
exit 1
