#!/usr/bin/env bash
# Update pi-mcp-adapter.nix and pi-mcp-adapter-lock.json to the latest release.
# The upstream repo ships no package-lock.json, so we generate one here with
# --omit=dev --omit=peer for the build. npm can still leave omitted dev
# dependency metadata in package-lock.json; repair any registry entries that
# lack integrity so prefetch-npm-deps can parse the lockfile.
#
# Usage: ./apps/fetcher/update-pi-mcp-adapter.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PIN_FILE="$SCRIPT_DIR/pi-mcp-adapter.nix"
LOCK_FILE="$SCRIPT_DIR/pi-mcp-adapter-lock.json"

PKG="pi-mcp-adapter"
REPO="nicobailon/pi-mcp-adapter"

echo "Resolving latest $PKG ..."
version=$(npm view "$PKG" version)
echo "  version: $version"

echo "Fetching source hash ..."
hash=$(nix run nixpkgs#nurl -- "https://github.com/$REPO" "v$version" 2>/dev/null \
  | grep 'hash =' | sed 's/.*hash = "\(.*\)".*/\1/')
echo "  hash: $hash"

echo "Generating lockfile (--omit=dev --omit=peer) ..."
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
srcPath=$(nix flake prefetch --json "github:$REPO/v$version" | jq -r .storePath)
cp -r "$srcPath"/. "$tmp/"
chmod -R u+w "$tmp"
cd "$tmp"
npm install --ignore-scripts --omit=dev --omit=peer -q 2>&1 | tail -2

missing_integrity_count=$(node <<'NODE'
const fs = require('fs');
const lock = JSON.parse(fs.readFileSync('package-lock.json', 'utf8'));
const missing = Object.entries(lock.packages ?? {}).filter(([, pkg]) =>
  pkg.resolved && !pkg.integrity && !pkg.resolved.startsWith('git+')
);
console.log(missing.length);
NODE
)

if [[ "$missing_integrity_count" != "0" ]]; then
  echo "Repairing $missing_integrity_count lockfile entries missing integrity ..."
  node <<'NODE'
const {execFileSync} = require('child_process');
const fs = require('fs');

const lockFile = 'package-lock.json';
const lock = JSON.parse(fs.readFileSync(lockFile, 'utf8'));

function packageNameFromLockPath(pkgPath) {
  const lastNodeModules = pkgPath.split('node_modules/').pop();
  const parts = lastNodeModules.split('/');
  return parts[0].startsWith('@') ? `${parts[0]}/${parts[1]}` : parts[0];
}

let repaired = 0;
for (const [pkgPath, pkg] of Object.entries(lock.packages ?? {})) {
  if (!pkg.resolved || pkg.integrity || pkg.resolved.startsWith('git+')) {
    continue;
  }

  const name = packageNameFromLockPath(pkgPath);
  const spec = `${name}@${pkg.version}`;
  const output = execFileSync('npm', ['view', spec, 'dist.integrity', '--json'], {
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'inherit'],
  }).trim();
  const integrity = JSON.parse(output);
  if (typeof integrity !== 'string' || integrity.length === 0) {
    throw new Error(`No registry integrity found for ${spec}`);
  }
  pkg.integrity = integrity;
  repaired += 1;
}

fs.writeFileSync(lockFile, `${JSON.stringify(lock, null, 2)}\n`);
console.log(`  repaired ${repaired} entries`);
NODE
fi

cp package-lock.json "$LOCK_FILE"
echo "  lockfile written to $LOCK_FILE"

echo "Computing npmDepsHash ..."
npmDepsHash=$(nix run nixpkgs#prefetch-npm-deps -- "$LOCK_FILE" 2>/dev/null)
echo "  npmDepsHash: $npmDepsHash"

cat > "$PIN_FILE" <<EOF
# Auto-generated by update-pi-mcp-adapter.sh
# Pins the nicobailon/pi-mcp-adapter GitHub source for buildNpmPackage.
# Lockfile: pi-mcp-adapter-lock.json (generated; upstream repo has no lockfile).
# Do not edit by hand; run ./apps/fetcher/update-pi-mcp-adapter.sh.
{
  version = "$version";
  hash = "$hash";
  npmDepsHash = "$npmDepsHash";
}
EOF

alejandra --quiet "$PIN_FILE" 2>/dev/null || true
echo "Updated $PIN_FILE ($PKG $version)"
