#!/usr/bin/env bash
# Update pi-rpiv-todo.nix and pi-rpiv-todo-lock.json to the latest release.
#
# The package lives in the juicesharp/rpiv-mono monorepo at
# packages/rpiv-todo. We fetch the full repo, extract just that subdir,
# then generate a lockfile with --omit=peer (peer deps are provided by
# pi core at runtime).
#
# Usage: ./apps/fetcher/update-pi-rpiv-todo.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PIN_FILE="$SCRIPT_DIR/pi-rpiv-todo.nix"
LOCK_FILE="$SCRIPT_DIR/pi-rpiv-todo-lock.json"

NPM_PKG="@juicesharp/rpiv-todo"
REPO="juicesharp/rpiv-mono"
SUBDIR="packages/rpiv-todo"

echo "Resolving latest $NPM_PKG ..."
version=$(npm view "$NPM_PKG" version)
echo "  version: $version"

echo "Fetching source hash ..."
hash=$(nix run nixpkgs#nurl -- "https://github.com/$REPO" "v$version" 2>/dev/null \
  | grep 'hash =' | sed 's/.*hash = "\(.*\)".*/\1/')
echo "  hash: $hash"

echo "Generating lockfile (--omit=peer) ..."
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
srcPath=$(nix flake prefetch --json "github:$REPO/v$version" | jq -r .storePath)
cp -r "$srcPath/$SUBDIR"/. "$tmp/"
chmod -R u+w "$tmp"
cd "$tmp"
npm install --ignore-scripts --omit=peer -q 2>&1 | tail -2
cp package-lock.json "$LOCK_FILE"
echo "  lockfile written to $LOCK_FILE"

echo "Computing npmDepsHash ..."
npmDepsHash=$(nix run nixpkgs#prefetch-npm-deps -- "$LOCK_FILE" 2>/dev/null)
echo "  npmDepsHash: $npmDepsHash"

cat > "$PIN_FILE" <<EOF
# Auto-generated by update-pi-rpiv-todo.sh
# Pins the juicesharp/rpiv-mono GitHub source (subdir packages/rpiv-todo)
# for buildNpmPackage.
# Lockfile: pi-rpiv-todo-lock.json (generated; upstream has no lockfile).
# Do not edit by hand; run ./apps/fetcher/update-pi-rpiv-todo.sh.
{
  version = "$version";
  hash = "$hash";
  npmDepsHash = "$npmDepsHash";
}
EOF

alejandra --quiet "$PIN_FILE" 2>/dev/null || true
echo "Updated $PIN_FILE ($NPM_PKG $version)"
