#!/usr/bin/env bash
# Update pi-dynamic-workflows.nix with the latest @quintinshaw/pi-dynamic-workflows
# release and its runtime dependency (acorn). Pi loads this as a local-path
# package and does not run npm install for it, so we pin both tarballs and the
# derivation (../pi-dynamic-workflows.nix) assembles node_modules itself.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NIX_FILE="$SCRIPT_DIR/pi-dynamic-workflows.nix"

prefetch() { # name -> prints "version url hash"
  local pkg="$1" version url hash
  version=$(npm view "$pkg" version --json | jq -r 'if type=="array" then last else . end')
  url=$(npm view "$pkg" dist.tarball --json | jq -r 'if type=="array" then last else . end')
  hash=$(nix store prefetch-file --json "$url" | jq -r '.hash')
  echo "$version" "$url" "$hash"
}

echo "Resolving @quintinshaw/pi-dynamic-workflows ..."
read -r wf_version wf_url wf_hash < <(prefetch "@quintinshaw/pi-dynamic-workflows")

# Track the acorn major range the package declares (acorn: ^8) to stay compatible.
acorn_range=$(npm view "@quintinshaw/pi-dynamic-workflows@${wf_version}" dependencies.acorn)
echo "Resolving acorn (${acorn_range}) ..."
read -r ac_version ac_url ac_hash < <(prefetch "acorn@${acorn_range}")

cat > "$NIX_FILE" <<EOF
# Auto-generated by update-pi-dynamic-workflows.sh
# Pins the @quintinshaw/pi-dynamic-workflows npm tarball plus its single runtime
# dependency (acorn). Assembled into a loadable pi package by
# ../pi-dynamic-workflows.nix. Do not edit by hand; run the updater.
{
  workflows = {
    version = "${wf_version}";
    url = "${wf_url}";
    hash = "${wf_hash}";
  };
  acorn = {
    version = "${ac_version}";
    url = "${ac_url}";
    hash = "${ac_hash}";
  };
}
EOF

alejandra --quiet "$NIX_FILE"
echo "Updated $NIX_FILE (workflows ${wf_version}, acorn ${ac_version})"
