#!/usr/bin/env bash
# Update pi-web-access.nix and pi-web-access-lock.json to the latest release.
# The upstream repo ships no package-lock.json, so we generate one here with
# --omit=peer (peer deps are provided by pi core at runtime).
#
# Usage: ./apps/fetcher/update-pi-web-access.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PIN_FILE="$SCRIPT_DIR/pi-web-access.nix"
LOCK_FILE="$SCRIPT_DIR/pi-web-access-lock.json"

PKG="pi-web-access"
REPO="nicobailon/pi-web-access"

echo "Resolving latest $PKG ..."
version=$(npm view "$PKG" version)
echo "  version: $version"

echo "Fetching source hash ..."
hash=$(nix run nixpkgs#nurl -- "https://github.com/$REPO" "v$version" 2>/dev/null \
  | grep 'hash =' | sed 's/.*hash = "\(.*\)".*/\1/')
echo "  hash: $hash"

echo "Generating lockfile (--omit=peer) ..."
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
srcPath=$(nix flake prefetch --json "github:$REPO/v$version" | jq -r .storePath)
cp -r "$srcPath"/. "$tmp/"
chmod -R u+w "$tmp"
cd "$tmp"
npm install --ignore-scripts --omit=peer -q 2>&1 | tail -2
cp package-lock.json "$LOCK_FILE"
echo "  lockfile written to $LOCK_FILE"

echo "Computing npmDepsHash ..."
npmDepsHash=$(nix run nixpkgs#prefetch-npm-deps -- "$LOCK_FILE" 2>/dev/null)
echo "  npmDepsHash: $npmDepsHash"

cat > "$PIN_FILE" <<EOF
# Auto-generated by update-pi-web-access.sh
# Pins the nicobailon/pi-web-access GitHub source for buildNpmPackage.
# Lockfile: pi-web-access-lock.json (generated; upstream repo has no lockfile).
# Do not edit by hand; run ./apps/fetcher/update-pi-web-access.sh.
{
  version = "$version";
  hash = "$hash";
  npmDepsHash = "$npmDepsHash";
}
EOF

alejandra --quiet "$PIN_FILE" 2>/dev/null || true
echo "Updated $PIN_FILE ($PKG $version)"
